### PR TITLE
Feature/imagearcgisrest

### PR DESCRIPTION
**Pull request by reed-tom**
Added support for ImageArcGISRest layers

### CODE REVIEW

**Review by jahow — COMMENTED** [review]
Hey, thanks a lot for this clean & tidy contribution! I was going to approve but the tests seem to be failing. For rendering tests we need to add local data here: https://github.com/camptocamp/inkmap/tree/main/test/rendering/data
so as not to rely on external services, maybe this is what's missing?

**Comment by reed-tom** [comment]
I'm been trying to resolve this issue, but I'm running into a problem with the test:rendering step.  I've run --fix to generate a new image for the new test case, however cases 01 - 05.1 seem to show an error percentage between 0.35-0.57%
I've tried running this step with multiple versions of node across a couple machines.  I've also tried pulling a fresh copy of the main branch and the render tests still come out with a variance.

**Comment by reed-tom** [comment]
[rerendered-expected-images.zip](https://github.com/camptocamp/inkmap/files/15278666/rerendered-expected-images.zip)
Attached the re-rendered versions of the cases that are failing for me.

**Comment by reed-tom** [comment]
Removed attribution from my test case as it turns out there was a difference with the font when run locally vs through github

**Review by jahow — APPROVED** [review]
Thank you! such a nice and tidy contribution :)

**Comment by jahow** [comment]
Let me know if you'd need this to be in a release, there hasn't been any in a while and with #66 also in the work it would make for a nice new release!

**Comment by reed-tom** [comment]
I'm working on adding a few more features, so more pull requests should be incoming, but please release at your discretion.

**Comment by jahow** [comment]
looking forward to it!

**Pull request merged**
