### PR TITLE
Add a jsconfig.json file and improve typing

### PR DESCRIPTION
**Pull request by fredj**
far for finished by that's a start

### CODE REVIEW

**Comment by jahow** [comment]
Nice! this should help checking types with tsc. Have you tried running it?

Note that the deploy phase of the CI fails for PR based on forked repos, we'll have to fix this.

**Comment by fredj** [comment]
> Nice! this should help checking types with tsc. Have you tried running it?

no I didn't; I only fixes some issue that was "red" in vscode

**Comment by fredj** [comment]
@jahow I won't add more to this PR; fell free to commit !

**Comment by jahow** [comment]
I've tried fixing some more type errors... TSC is really a nightmare to configure though.

**Comment by jahow** [comment]
This PR is ready, it also contains several fixes to make the WFS layers and raster reprojection work in the worker.

**Comment by jahow** [comment]
thanks @fredj !

**Pull request merged**
